version: '3.0'  # 使用 Docker Compose 的版本 3.0，適合大部分部署場景



services:
  crawler_twse:
    image: peiyuji/web_crawler_us:${DOCKER_IMAGE_VERSION}
    hostname: "twse"
    command: pipenv run celery -A crawler.worker worker -Q twse --loglevel=info --hostname=%h
    restart: always
    environment:
      - TZ=Asia/Taipei
    networks:
      - my_network

  crawler_tpex:
    image: peiyuji/web_crawler_us:${DOCKER_IMAGE_VERSION}
    hostname: "tpex"
    command: pipenv run celery -A crawler.worker worker -Q tpex --loglevel=info --hostname=%h
    restart: always
    environment:
      - TZ=Asia/Taipei
    networks:
      - my_network

  crawler_US_ETF_list:
    image: peiyuji/web_crawler_us:${DOCKER_IMAGE_VERSION}
    hostname: "US_ETF_list"
    command: pipenv run celery -A crawler.worker worker -Q US_ETF_list --loglevel=info --hostname=%h
    restart: always
    environment:
      - TZ=Asia/Taipei
    networks:
      - my_network

networks:
  my_network:
    external: true
