version: '3.0'  # 使用 Docker Compose 的版本 3.0，適合大部分部署場景

services:
  crawler_producer:  # 定義一個服務
    image: peiyuji/web_crawler_us:${DOCKER_IMAGE_VERSION}  # 使用的映像檔名稱與標籤（版本）
    hostname: "crawler_producer"  # 設定 hostname
    command: pipenv run python crawler/US_EFT_Yahoo_1.py
    # restart: always  # 若容器停止或崩潰，自動重新啟動
    environment:
      - TZ=Asia/Taipei  # 設定時區為台北（UTC+8）
    networks:
      - etf_lib_network  # 將此服務連接到 etf_lib_network 網路

networks:
  etf_lib_network:
    # 加入已經存在的網路
    external: true